### ISSUE TITLE
Unresolved dependency: org.scalaz.stream#scalaz-stream_2.11;0.7a: not found

### ISSUE THREAD

**Issue by sparrovv** [solarmosaic/utility-api-client#1]
Hi there, when compiling master branch I'm getting:

``` sh
[info] Resolving org.scalaz.stream#scalaz-stream_2.11;0.7a ...
[warn] Host art.intranet.solarmosaic.com not found. url=http://art.intranet.solarmosaic.com/artifactory/repo/org/scalaz/stream/scalaz-stream_2.11/0.7a/scalaz-stream_2.11-0.7a.pom
[info] You probably access the destination server through a proxy server that is not well configured.
[warn]  module not found: org.scalaz.stream#scalaz-stream_2.11;0.7a
[warn] ==== local: tried
[warn]   /Users/mwrobel/.ivy2/local/org.scalaz.stream/scalaz-stream_2.11/0.7a/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scalaz/stream/scalaz-stream_2.11/0.7a/scalaz-stream_2.11-0.7a.pom
[warn] ==== Artifactory: tried
[warn]   http://art.intranet.solarmosaic.com/artifactory/repo/org/scalaz/stream/scalaz-stream_2.11/0.7a/scalaz-stream_2.11-0.7a.pom
[info] Resolving jline#jline;2.12 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scalaz.stream#scalaz-stream_2.11;0.7a: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]      org.scalaz.stream:scalaz-stream_2.11:0.7a
[warn]        +- org.specs2:specs2-common_2.11:3.3
[warn]        +- org.specs2:specs2-matcher_2.11:3.3
[warn]        +- org.specs2:specs2-core_2.11:3.3 (/Users/mwrobel/workspace/gh/utility-api-client/build.sbt#L19)
[warn]        +- org.specs2:specs2-mock_2.11:3.3 (/Users/mwrobel/workspace/gh/utility-api-client/build.sbt#L19)
[warn]        +- com.solarmosaic.client:utility-api-client_2.11:0.1.0-SNAPSHOT
sbt.ResolveException: unresolved dependency: org.scalaz.stream#scalaz-stream_2.11;0.7a: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
    at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
    at sbt.IvySbt.withIvy(Ivy.scala:127)
    at sbt.IvySbt.withIvy(Ivy.scala:124)
    at sbt.IvySbt$Module.withModule(Ivy.scala:155)
    at sbt.IvyActions$.updateEither(IvyActions.scala:165)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.scalaz.stream#scalaz-stream_2.11;0.7a: not found
[error] Total time: 3 s, completed 08-Sep-2015 23:03:00
```

**Comment by kflorence** [comment]
@sparrovv You will need to add `bintray` to your sbt build file (you can also remove `art.intranet.solarmosaic` as that is our internal artifactory cache):

```
resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"
```

**Comment by kflorence** [comment]
@sparrovv Also, in the future, we should have this published in Maven so you can just include it as a dependency instead of having to build it yourself. Sorry about that! :)

**Comment by sparrovv** [comment]
Hey @kflorence no worries. I'm mostly interested in this repo from the technical PoV, as I'm going to work on the API client that will use spray and your implementation looks good.

Thanks for coming back to me, it compiles now.

**Comment by kflorence** [comment]
@sparrovv no worries. I will be pushing some changes here later today to address this problem for others. I am also switching from using Spray's [Host-level API](http://spray.readthedocs.org/en/latest/documentation/spray-can/http-client/host-level.html) to their [Request-level API](http://spray.readthedocs.org/en/latest/documentation/spray-can/http-client/request-level.html) -- the major perk of this is that when using the Request-level API we don't have to manage connection timeouts (plus the syntax is just simpler).
